name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: kirandevops1993/Repo-B/.github/workflows/reusable-ci.yml@main
    with:
      repo_url: "https://github.com/kirandevops1993/REPO-A.git"
      maven-goal: "clean install"
    env:
      MAVEN_OPTS: "-Xmx1024m"
    timeout-minutes: 10
    continue-on-error: false
    permissions:
      contents: read
    concurrency:
      group: ci-pipeline
      cancel-in-progress: true

  setup-environment:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
      - name: Setup Environment Variables
        run: echo "Setting up environment variables"
        env:
          ENV_TYPE: "production"
        timeout-minutes: 2

  notify:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    if: success()
    steps:
      - name: Send Notification
        run: echo "Build Successful!"
        continue-on-error: true
