name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: kirandevops1993/Repo-B/.github/workflows/reusable-ci.yml@main

    with:
      repo_url: https://github.com/kirandevops1993/REPO-A.git
      maven-goal: "Build"



    
   
      
