name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: kirandevops1993/Repo-B/.github/workflows/reusable-ci.yml@main
    with:
      repo_url: "https://github.com/kirandevops1993/REPO-A.git"
      maven-goal: "clean install"

  setup-environment:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
      - name: Setup Environment Variables
        run: echo "Setting up environment variables"
        env:
          ENV_TYPE: "production"
    timeout-minutes: 2

  notify:
    runs-on: ubuntu-latest
    needs: [call-reusable-workflow, setup-environment]
    steps:
      - name: Send Notification
        run: echo "Build Successful!"
        continue-on-error: true
